"""
Phase 11 Orchestration: Intelligent Repository-Level Code Review.

Coordinates context gathering, prompt building, LLM execution,
evidence validation, severity ranking, and review report generation.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Optional

from repopilot.exceptions import ReviewError
from repopilot.groq_provider import GroqProvider
from repopilot.llm_provider import LLMProvider
from repopilot.models import (
    AgentResult,
    FileDiff,
    FindingKind,
    RepositoryModel,
    ReviewCategory,
    ReviewFinding,
    ReviewMode,
    ReviewReport,
    ReviewRequest,
    ReviewSeverity,
)
from repopilot.prompt_builder import PromptBuilder
from repopilot.review_context_builder import ReviewContextBuilder

_SEVERITY_ORDER = {
    ReviewSeverity.CRITICAL.value: 0,
    ReviewSeverity.HIGH.value: 1,
    ReviewSeverity.MEDIUM.value: 2,
    ReviewSeverity.LOW.value: 3,
    ReviewSeverity.INFO.value: 4,
}


class ReviewService:
    """Orchestrates Phase 11 intelligent code review."""

    def __init__(
        self,
        context_builder: Optional[ReviewContextBuilder] = None,
        llm_provider: Optional[LLMProvider] = None,
    ):
        self._llm_provider = llm_provider or GroqProvider()
        self._context_builder = context_builder or ReviewContextBuilder()

    def review(self, request: ReviewRequest, repo_model: RepositoryModel) -> ReviewReport:
        """Execute a review workflow according to the ReviewRequest."""
        if request is None:
            raise ReviewError("A non-empty ReviewRequest is required.")
        if repo_model is None:
            raise ReviewError("A RepositoryModel is required for code review.")

        mode = request.mode if isinstance(request.mode, ReviewMode) else ReviewMode(request.mode)

        # 1. Deterministic Context Gathering
        context_text = self._context_builder.build(repo_model, request)

        # 2. Prompt Building
        if mode == ReviewMode.DIFF:
            system_prompt, user_prompt = PromptBuilder.build_review_diff(context_text, request)
        else:
            system_prompt, user_prompt = PromptBuilder.build_review_full_repo(context_text, request)

        # 3. LLM Generation
        raw_response = self._llm_provider.generate(system_prompt, user_prompt)

        # 4. Defensive Parsing & Normalization
        parsed_data = self._parse_json_response(raw_response)

        # 5. Extract & Validate Findings
        findings, system_warnings = self._build_and_validate_findings(parsed_data, repo_model)

        # 6. Rank Findings by Severity
        findings.sort(key=lambda f: _SEVERITY_ORDER.get(f.severity, 99))

        # 7. Compute Statistics
        severity_counts = {sev.value: 0 for sev in ReviewSeverity}
        category_counts: dict[str, int] = {}
        for f in findings:
            severity_counts[f.severity] = severity_counts.get(f.severity, 0) + 1
            category_counts[f.category] = category_counts.get(f.category, 0) + 1

        # 8. Reviewed files
        if mode == ReviewMode.DIFF:
            diffs = list(request.diffs)
            if request.agent_result and request.agent_result.diffs:
                diffs.extend(request.agent_result.diffs)
            reviewed_files = sorted(set(d.file_path for d in diffs))
            if not reviewed_files and request.target_files:
                reviewed_files = list(request.target_files)
        else:
            reviewed_files = [f.path for f in repo_model.files]

        all_warnings = list(parsed_data.get("warnings", [])) + system_warnings
        passed_checks = list(parsed_data.get("passed_checks", []))
        summary = str(parsed_data.get("summary", "Review completed successfully."))

        return ReviewReport(
            mode=mode.value,
            summary=summary,
            findings=findings,
            severity_counts=severity_counts,
            category_counts=category_counts,
            reviewed_files=reviewed_files,
            passed_checks=passed_checks,
            warnings=all_warnings,
        )

    def review_agent_result(
        self,
        agent_result: AgentResult,
        repo_model: RepositoryModel,
        focus_categories: Optional[list[str]] = None,
        custom_instructions: Optional[str] = None,
    ) -> ReviewReport:
        """Convenience method to review an AgentResult generated by Phase 10."""
        request = ReviewRequest(
            mode=ReviewMode.DIFF,
            agent_result=agent_result,
            diffs=list(agent_result.diffs),
            focus_categories=focus_categories or [],
            custom_instructions=custom_instructions,
        )
        return self.review(request, repo_model)

    def review_diffs(
        self,
        diffs: list[FileDiff],
        repo_model: RepositoryModel,
        focus_categories: Optional[list[str]] = None,
        custom_instructions: Optional[str] = None,
    ) -> ReviewReport:
        """Convenience method to review arbitrary FileDiffs."""
        request = ReviewRequest(
            mode=ReviewMode.DIFF,
            diffs=diffs,
            focus_categories=focus_categories or [],
            custom_instructions=custom_instructions,
        )
        return self.review(request, repo_model)

    def review_repository(
        self,
        repo_model: RepositoryModel,
        focus_categories: Optional[list[str]] = None,
        custom_instructions: Optional[str] = None,
    ) -> ReviewReport:
        """Convenience method for a full repository audit."""
        request = ReviewRequest(
            mode=ReviewMode.FULL_REPO,
            focus_categories=focus_categories or [],
            custom_instructions=custom_instructions,
        )
        return self.review(request, repo_model)

    @staticmethod
    def _parse_json_response(raw: str) -> dict:
        """Extract and parse JSON object safely from LLM output."""
        text = raw.strip()
        if text.startswith("```"):
            lines = text.splitlines()
            if lines[0].startswith("```"):
                lines = lines[1:]
            if lines and lines[-1].strip() == "```":
                lines = lines[:-1]
            text = "\n".join(lines).strip()

        try:
            data = json.loads(text)
            if not isinstance(data, dict):
                raise ReviewError(f"Expected a JSON object from LLM review, got {type(data).__name__}")
            return data
        except json.JSONDecodeError as exc:
            raise ReviewError(f"Failed to parse LLM review output as JSON: {exc}\nRaw content:\n{raw[:300]}")

    @staticmethod
    def _build_and_validate_findings(
        data: dict, repo_model: RepositoryModel
    ) -> tuple[list[ReviewFinding], list[str]]:
        """Validate findings against repository ground truths."""
        raw_findings = data.get("findings", [])
        if not isinstance(raw_findings, list):
            return [], [f"Malformed 'findings' in review output; expected list, got {type(raw_findings).__name__}"]

        valid_file_paths = {f.path.replace("\\", "/").lower() for f in repo_model.files}
        known_severities = {s.value for s in ReviewSeverity}
        known_categories = {c.value for c in ReviewCategory}
        known_kinds = {k.value for k in FindingKind}

        validated: list[ReviewFinding] = []
        warnings: list[str] = []

        for item in raw_findings:
            if not isinstance(item, dict):
                continue

            category = str(item.get("category", ReviewCategory.CODE_QUALITY.value)).upper()
            if category not in known_categories:
                category = ReviewCategory.CODE_QUALITY.value

            severity = str(item.get("severity", ReviewSeverity.MEDIUM.value)).upper()
            if severity not in known_severities:
                severity = ReviewSeverity.MEDIUM.value

            finding_kind = str(item.get("finding_kind", FindingKind.INFERENCE.value)).upper()
            if finding_kind not in known_kinds:
                finding_kind = FindingKind.INFERENCE.value

            file_path = item.get("file_path")
            if file_path:
                norm_fp = str(file_path).replace("\\", "/").lower()
                # Check if cited file exists in repo
                if valid_file_paths and norm_fp not in valid_file_paths:
                    # Check substring match for relative path
                    if not any(vf.endswith(norm_fp) or norm_fp.endswith(vf) for vf in valid_file_paths):
                        warnings.append(
                            f"Finding '{item.get('title', 'Untitled')}' referenced non-existent repository path: {file_path}"
                        )

            finding = ReviewFinding(
                category=category,
                severity=severity,
                title=str(item.get("title", "Review Finding")),
                description=str(item.get("description", "")),
                file_path=file_path,
                line_number=item.get("line_number"),
                start_line=item.get("start_line"),
                end_line=item.get("end_line"),
                snippet=item.get("snippet"),
                evidence=str(item.get("evidence", "")),
                finding_kind=finding_kind,
                recommendation=str(item.get("recommendation", "")),
                confidence=str(item.get("confidence", "HIGH")),
            )
            validated.append(finding)

        return validated, warnings
